# Generated by Django 4.2.28 on 2026-02-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_image', models.ImageField(blank=True, null=True, upload_to='attendance/clock_in/')),
                ('clock_out_image', models.ImageField(blank=True, null=True, upload_to='attendance/clock_out/')),
                ('status', models.CharField(default='Present', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-clock_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
