# Generated by Django 4.2.28 on 2026-02-25 13:01

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_hub_manager_employee_cr_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.attendance_clock_in_path),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.attendance_clock_out_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.profile_picture_path),
        ),
    ]
