# Generated by Django 5.0.9 on 2026-04-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employee_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
