# Generated by Django 5.0.9 on 2026-05-15 04:14

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_activitylog_action_freeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.attendance_clock_in_path),
        ),
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=employees.models.saved_image_path)),
                ('image_type', models.CharField(choices=[('profile', 'Profile Picture'), ('edit_request', 'Edit Request Image'), ('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('leave_attachment', 'Leave Request Attachment'), ('payslip', 'Payslip')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_images', to='employees.attendance')),
                ('edit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_images', to='employees.editrequest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_images', to='employees.employee')),
                ('leave_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_images', to='employees.leaveattachment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'image_type'], name='employees_s_employe_8cfd3a_idx'), models.Index(fields=['employee', 'created_at'], name='employees_s_employe_91fe7d_idx')],
            },
        ),
    ]
