# Generated by Django 5.0.9 on 2026-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_payroll_adjustment_payroll_convenience_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resign', 'Resign'), ('AWOL', 'AWOL'), ('Blacklist', 'Blacklist')], default='Active', max_length=20),
        ),
    ]
