# Generated by Django 5.0.14 on 2026-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
