services:
  - type: web
    name: 3pl-ostaga-thesis-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 4 --worker-class gthread --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: CONN_MAX_AGE
        value: "600"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: ALLOWED_HOSTS
        value: .onrender.com,*.vercel.app,cj-3pl-ostaga.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,https://*.vercel.app,https://cj-3pl-ostaga.vercel.app
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: "^https://.*\\.vercel\\.app$"

