"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY fallback for local development when env var isn't set
# In production, always set the `SECRET_KEY` environment variable to a
# long, random value. The fallback below is long enough to satisfy
# Django system checks during development but must NOT be used in
# production deployments.
SECRET_KEY = os.environ.get('SECRET_KEY') or 'dev-insecure-please-set-SECRET_KEY-2026-06-01-CHANGE_ME-xxxxxxxxxxxx'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = 'DENY'

# Security-related settings: allow environment overrides but default to
# secure values when running with DEBUG=False (production mode).
# You can override these via environment variables if needed.
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000')) if not DEBUG else int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True' if not DEBUG else 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').lower() in ('1', 'true', 'yes')
# Read from env var for flexibility, default to hardcoded for production
_ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '').strip()
if _ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in _ALLOWED_HOSTS_ENV.split(',')]
else:
    ALLOWED_HOSTS = [
    "threepl-backend-wf79.onrender.com",
    ".vercel.app",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'employees',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'employees.middleware.CheckActiveUserMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL exclusively. Set DATABASE_URL in environment or fallback to local DB.
_DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
# For local development, fallback to a sqlite DB if no DATABASE_URL provided
if not _DATABASE_URL:
    _DATABASE_URL = f'sqlite:///{BASE_DIR / "db.sqlite3"}'

import dj_database_url

# Allow tuning of connection pooling and SSL via env vars
_CONN_MAX_AGE = int(os.environ.get('CONN_MAX_AGE', '600'))
# For local dev without SSL, you might want to set DB_SSL_REQUIRE=False or default to False if DATABASE_URL is local.
# We'll default to False for the fallback but respect env var.
_default_ssl = 'False' if 'localhost' in _DATABASE_URL or '127.0.0.1' in _DATABASE_URL else 'True'
_DB_SSL_REQUIRE = os.environ.get('DB_SSL_REQUIRE', _default_ssl).lower() in ('1', 'true', 'yes')

if _DATABASE_URL.startswith('sqlite'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=_DATABASE_URL,
            conn_max_age=_CONN_MAX_AGE,
            ssl_require=_DB_SSL_REQUIRE,
        )
    }

CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    "https://threepl-backend-wf79.onrender.com",
]
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # ✅ ADD THIS HERE
    ],
}

# Simple JWT settings — increase access token lifetime to 30 minutes to reduce
# unexpected short logouts from the frontend.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

#  settings - allow frontend to communicate
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "https://3-plcjfinal-79xnpq3is-cj-g-a-js-projects.vercel.app",  # Old Vercel frontend
    "https://3-plcj-again.vercel.app",  # ✅ Current Vercel frontend
]
# Production + preview deployments on Vercel (URLs change per branch)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# Allow environment to override CORS settings if needed
_CORS_ORIGINS_ENV = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _CORS_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in _CORS_ORIGINS_ENV.split(',')])

CORS_ALLOW_CREDENTIALS = True

# Ensure common headers (including Authorization) are allowed in CORS preflight
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]

# Media files (for image uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Persistent media storage configuration
# Set MEDIA_STORAGE env var to 's3' to use Amazon S3 via django-storages,
# otherwise files will be stored on the local filesystem under MEDIA_ROOT.
_MEDIA_STORAGE = os.environ.get('MEDIA_STORAGE', 'local').lower()
if _MEDIA_STORAGE == 's3':
    # Use django-storages S3 backend. Ensure django-storages[boto3] and boto3
    # are installed in your environment when enabling S3.
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME') or None
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None

    # Recommended settings for uploads
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False

    # If a custom domain is provided, use it as MEDIA_URL; otherwise build default
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    elif AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME:
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
    elif AWS_STORAGE_BUCKET_NAME:
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'
    else:
        # leave MEDIA_URL as default; storage backend will raise if bucket missing
        pass
else:
    # Local filesystem (default)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Used when building media URLs without an HTTP request (and as fallback). Set on Render, e.g.
# PUBLIC_SITE_URL=https://your-service.onrender.com
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', '').strip().rstrip('/')
if not PUBLIC_SITE_URL:
    for host in ALLOWED_HOSTS:
        if host and host != '*' and not host.startswith('.'):
            PUBLIC_SITE_URL = f'https://{host}'
            break

# Default government deduction rates (percentages). These are applied to total earnings
# and are read-only for payslip calculations. Adjust here if needed site-wide.
DEFAULT_GOV_RATES = {
    'sss': 4.5,
    'philhealth': 2.75,
    'pagibig': 1.0,
}

# Optional per-hub override. Example:
# HUB_DEDUCTION_RATES = {
#     'Quezon Hub': {'sss': 4.5, 'philhealth': 2.75, 'pagibig': 1.0},
# }
HUB_DEDUCTION_RATES = {}
