# Generated by Django 4.2.28 on 2026-02-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_hub_manager_employee_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hub_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='cr_number',
            field=models.CharField(blank=True, help_text='CR (Certificate of Registration) number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='desired_work_location',
            field=models.ForeignKey(blank=True, help_text='Desired work location or branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_by_employees', to='employees.hub'),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license',
            field=models.CharField(blank=True, help_text="Driver's license number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_expiry',
            field=models.DateField(blank=True, help_text="Driver's license expiry date", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_address',
            field=models.TextField(blank=True, help_text="Family address (if different from employee's current address)", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='government_id',
            field=models.CharField(blank=True, help_text="Government-issued ID (driver's license, national ID, etc.)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nbi_clearance',
            field=models.CharField(blank=True, help_text='NBI or police clearance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='or_number',
            field=models.CharField(blank=True, help_text='OR (Official Receipt) number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig',
            field=models.CharField(blank=True, help_text='Pag-IBIG number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent address', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth',
            field=models.CharField(blank=True, help_text='PhilHealth number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Plate number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='previous_work_experience',
            field=models.TextField(blank=True, help_text='Previous work experience (especially courier/delivery jobs)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='proof_of_ownership',
            field=models.TextField(blank=True, help_text='Proof of ownership or authorization to use the vehicle', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_date_of_birth',
            field=models.DateField(blank=True, help_text="Spouse's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, help_text="Spouse's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_phone',
            field=models.CharField(blank=True, help_text="Spouse's contact number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss',
            field=models.CharField(blank=True, help_text='SSS number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Current address', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('OIC', 'OIC')], default='Full-time', max_length=20),
        ),
    ]
