# Generated by Django 4.2.28 on 2026-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_attendance_clock_in_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='children_info',
            field=models.TextField(blank=True, help_text='Children information (JSON format: name, date_of_birth)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_image',
            field=models.ImageField(blank=True, help_text="Driver's license image", null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='government_id_image',
            field=models.ImageField(blank=True, help_text='Government-issued ID image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, help_text="Mother's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nbi_clearance_image',
            field=models.ImageField(blank=True, help_text='NBI clearance image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='or_cr_image',
            field=models.ImageField(blank=True, help_text='OR/CR document image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig_image',
            field=models.ImageField(blank=True, help_text='Pag-IBIG document image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_image',
            field=models.ImageField(blank=True, help_text='PhilHealth document image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='proof_of_ownership_image',
            field=models.ImageField(blank=True, help_text='Proof of ownership image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_address',
            field=models.TextField(blank=True, help_text="Spouse's address", null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_occupation',
            field=models.CharField(blank=True, help_text="Spouse's occupation", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_image',
            field=models.ImageField(blank=True, help_text='SSS document image', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_image',
            field=models.ImageField(blank=True, help_text='TIN document image', null=True, upload_to='documents/'),
        ),
    ]
