# Generated by Django 4.2.28 on 2026-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_children_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to support the edit request', null=True, upload_to='edit_requests/'),
        ),
    ]
