# Generated by Django 5.1.6 on 2026-04-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_attendance_options_alter_livelocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.hub'),
        ),
    ]
