# Generated by Django 5.0.9 on 2026-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
