# Generated by Django 5.0.9 on 2026-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_editrequest_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('OCW', 'OCW')], max_length=20),
        ),
    ]
