# Generated by Django 5.0.9 on 2026-04-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/clock_in/'),
        ),
    ]
