# Generated by Django 6.0.4 on 2026-05-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_rename_deductions_payroll_deduction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_edit_info',
            field=models.BooleanField(default=True),
        ),
    ]
