# Generated by Django 5.0.9 on 2026-05-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_can_edit_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_employees', models.BooleanField(default=False)),
                ('can_edit_employee_info', models.BooleanField(default=False)),
                ('can_edit_payslip', models.BooleanField(default=False)),
                ('can_delete_employees', models.BooleanField(default=False)),
                ('can_reset_password', models.BooleanField(default=False)),
                ('can_enable_employee_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_permissions', to='employees.employee')),
            ],
        ),
    ]
