# Generated by Django 5.0.9 on 2026-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_hrpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('create_employee', 'Create Employee'), ('update_employee', 'Update Employee'), ('delete_employee', 'Delete Employee'), ('approve_request', 'Approve Request'), ('reject_request', 'Reject Request'), ('view_profile', 'View Profile'), ('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('update_payslip', 'Update Payslip'), ('approve_payslip', 'Approve Payslip'), ('reset_password', 'Reset Password'), ('blacklist', 'Blacklist'), ('employee_deleted', 'Employee Deleted'), ('toggle_edit_permission', 'Toggle Edit Permission')], max_length=30),
        ),
    ]
