# Generated by Django 5.0.9 on 2026-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_alter_attendance_clock_in_image_savedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedimage',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
