# Generated by Django 5.0.14 on 2026-06-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_rename_current_address_employee_complete_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
