# Generated by Django 5.0.14 on 2026-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_alter_activitylog_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpermission',
            name='access_type',
            field=models.CharField(choices=[('Single', 'Single Hub Access'), ('Multiple', 'Multiple Hub Access')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='managed_hubs',
            field=models.ManyToManyField(blank=True, related_name='hr_managers', to='employees.hub'),
        ),
    ]
