# Generated by Django 5.0.14 on 2026-08-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_hrpermission_access_type_hrpermission_managed_hubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='complete_address',
        ),
    ]
