# Generated by Django 5.0.14 on 2026-08-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_remove_employee_complete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, help_text='Account Holder Name', max_length=150)),
                ('account_number', models.CharField(help_text='Mobile number, Bank Account, or Card number', max_length=100)),
                ('account_type', models.CharField(choices=[('Maya', 'Maya'), ('GCash', 'GCash'), ('Bank Card', 'Bank Card'), ('Credit Card/Debit Card', 'Credit Card/Debit Card')], max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Bank/Provider Name (e.g. BDO, BPI, UnionBank)', max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'account_type'], name='employees_p_employe_4930e6_idx'), models.Index(fields=['account_type'], name='employees_p_account_ebae0c_idx')],
            },
        ),
    ]
