# Generated by Django 5.0.14 on 2026-08-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_add_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(blank=True, default='document', max_length=50),
        ),
    ]
