# Generated by Django 5.0.14 on 2026-09-01 06:36

import django.db.models.deletion
import django.utils.timezone
import recruitment.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_number', models.CharField(blank=True, max_length=20)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('sss', models.CharField(blank=True, max_length=50)),
                ('philhealth', models.CharField(blank=True, max_length=50)),
                ('pagibig', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('preferred_hub', models.CharField(blank=True, max_length=200)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('driver_info', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('employment_history', models.JSONField(blank=True, null=True)),
                ('rejection_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=50)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=recruitment.models.application_document_upload_to)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.application')),
            ],
        ),
    ]
